apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-service.fullname" . }}
  labels:
    app: {{ include "application-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "application-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "application-service.name" . }}
    spec:
      {{- if .Values.global.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.global.serviceAccount.name | quote }}
      {{- end }}
      containers:
        - name: {{ include "application-service.name" . }}
          image: "{{ required "ERROR: image.repository is required" .Values.image.repository }}:{{ required "ERROR: image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
