image:
  repository: gcr.io/massive-sandbox-477717-k3/patient-service
  tag: "1.0"
  pullPolicy: IfNotPresent
service:
  port: 3000
replicaCount: 1
resources: {}
env: []
global:
  imagePullSecrets: []
  keyvault:
    enabled: false
