image:
  repository: us-central1-docker.pkg.dev/massive-sandbox-477717-k3/dev-docker/patient-service
  tag: sha-7ff788cd3de52002eb5da310773a985fec086c48
pullPolicy: IfNotPresent
service:
  port: 3000
replicaCount: 1
resources: {}
env: []
global:
  imagePullSecrets: []
  keyvault:
    enabled: false
