image:
  repository: us-central1-docker.pkg.dev/massive-sandbox-477717-k3/dev-docker/application-service
  tag: sha-node-fix

imagePullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 3000

resources: {}
env: []
