apiVersion: v1
kind: Service
metadata:
  name: {{ include "patient-service.fullname" . }}
  labels:
    app: {{ include "patient-service.name" . }}
spec:
  selector:
    app: {{ include "patient-service.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
  type: LoadBalancer

