name: Terraform Apply - Prod

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: massive-sandbox-477717-k3

jobs:
  terraform-apply-prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/envs/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_PROD }}
          service_account: github-terraform-prod@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.PROJECT_ID }}
          create_credentials_file: true
          export_environment_variables: true
          token_format: "access_token"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-prod
          path: infra/gcp/envs/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve infra/gcp/envs/prod/tfplan
