name: Terraform Apply - Dev

on:
  push:
    branches: [dev]
    paths:
      - 'infra/gcp/envs/dev/**'

env:
  PROJECT_ID: massive-sandbox-477717-k3

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/envs/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_DEV }}
          service_account: github-terraform-dev@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.PROJECT_ID }}

      - run: terraform init -backend-config=backend.hcl -input=false
      - run: terraform apply -auto-approve -input=false
