name: Terraform Plan - Staging

on:
  push:
    branches: [staging]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: massive-sandbox-477717-k3

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/envs/staging

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/661961012629/locations/global/workloadIdentityPools/github-pool-v4/providers/github-provider-staging
          service_account: github-terraform-staging@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.PROJECT_ID }}

      - run: terraform fmt -recursive
      - run: terraform init -backend-config=backend.hcl -input=false
      - run: terraform validate -no-color
      - run: terraform plan -out=tfplan -input=false -no-color
